// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace finenako_service_tests.Controllers
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Find many lease offers")]
    public partial class FindManyLeaseOffersFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "RetrieveLeaseOfferList.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Controllers", "Find many lease offers", "\tIn order to obtain a leas offer list", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list without any parameter")]
        public void RetrieveLeaseOfferListWithoutAnyParameter()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list without any parameter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table1.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table1.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
#line 5
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table1, "Given ");
#line hidden
#line 9
 testRunner.When("I make a GET request on lease-offers endpoint without any argument", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 11
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table2.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table2.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
#line 12
 testRunner.And("The pageable content items should be like :", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by leaseOfferId asc")]
        public void RetrieveLeaseOfferListOrderByLeaseOfferIdAsc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by leaseOfferId asc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table3.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "950"});
                table3.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "750"});
#line 18
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table3, "Given ");
#line hidden
#line 22
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=leaseOfferI" +
                        "d&order=Asc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table4.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "950"});
                table4.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "750"});
#line 25
 testRunner.And("The pageable content items should be like :", ((string)(null)), table4, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by leaseOfferId desc")]
        public void RetrieveLeaseOfferListOrderByLeaseOfferIdDesc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by leaseOfferId desc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table5.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table5.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
#line 31
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table5, "Given ");
#line hidden
#line 35
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=leaseOfferI" +
                        "d&order=Desc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table6.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table6.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
#line 38
 testRunner.And("The pageable content items should be like :", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by monthlyRent asc")]
        public void RetrieveLeaseOfferListOrderByMonthlyRentAsc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by monthlyRent asc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table7.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "950"});
                table7.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "750"});
#line 44
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table7, "Given ");
#line hidden
#line 48
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=monthlyRent" +
                        "&order=Asc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table8.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "750"});
                table8.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "950"});
#line 51
 testRunner.And("The pageable content items should be like :", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by monthlyRent desc")]
        public void RetrieveLeaseOfferListOrderByMonthlyRentDesc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by monthlyRent desc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table9.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table9.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
#line 57
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table9, "Given ");
#line hidden
#line 61
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=monthlyRent" +
                        "&order=Desc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table10.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table10.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
#line 64
 testRunner.And("The pageable content items should be like :", ((string)(null)), table10, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by surface asc")]
        public void RetrieveLeaseOfferListOrderBySurfaceAsc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by surface asc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table11.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table11.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
#line 70
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table11, "Given ");
#line hidden
#line 74
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=surface&ord" +
                        "er=Asc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table12.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table12.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
#line 77
 testRunner.And("The pageable content items should be like :", ((string)(null)), table12, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list order by surface desc")]
        public void RetrieveLeaseOfferListOrderBySurfaceDesc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list order by surface desc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table13.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
                table13.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "65",
                            "1",
                            "950"});
#line 83
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table13, "Given ");
#line hidden
#line 87
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=surface&ord" +
                        "er=Desc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 88
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 89
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table14.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "65",
                            "1",
                            "950"});
                table14.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
#line 90
 testRunner.And("The pageable content items should be like :", ((string)(null)), table14, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with both pagination and order")]
        public void RetrieveLeaseOfferListWithBothPaginationAndOrder()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with both pagination and order", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table15.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table15.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table15.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "18",
                            "1",
                            "1000"});
#line 96
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table15, "Given ");
#line hidden
#line 101
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'pageSize=2&page=2&o" +
                        "rderBy=leaseOfferId&order=Asc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 102
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
 testRunner.And("The pageable infos should be like : {CurrentPage : \'2\', TotalPage : \'2\', PageSize" +
                        " : \'2\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table16.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "18",
                            "1",
                            "1000"});
#line 104
 testRunner.And("The pageable content items should be like :", ((string)(null)), table16, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with page index higher than max")]
        public void RetrieveLeaseOfferListWithPageIndexHigherThanMax()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with page index higher than max", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 108
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table17.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
                table17.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
#line 109
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table17, "Given ");
#line hidden
#line 113
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'pageSize=2&page=2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 114
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'2\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table18.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "18",
                            "1",
                            "950"});
                table18.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "65",
                            "3",
                            "750"});
#line 116
 testRunner.And("The pageable content items should be like :", ((string)(null)), table18, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter on surfaceMin")]
        public void RetrieveLeaseOfferListWithFilterOnSurfaceMin()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter on surfaceMin", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table19.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
                table19.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
                table19.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "2",
                            "1000"});
#line 122
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table19, "Given ");
#line hidden
#line 127
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'surfaceMin=19\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 128
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 129
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table20.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "2",
                            "1000"});
                table20.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
#line 130
 testRunner.And("The pageable content items should be like :", ((string)(null)), table20, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter on roomsMax")]
        public void RetrieveLeaseOfferListWithFilterOnRoomsMax()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter on roomsMax", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 135
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table21.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "1",
                            "750"});
                table21.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "2",
                            "950"});
                table21.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "3",
                            "1000"});
#line 136
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table21, "Given ");
#line hidden
#line 141
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'roomsMax=2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 142
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table22.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "2",
                            "950"});
                table22.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "1",
                            "750"});
#line 144
 testRunner.And("The pageable content items should be like :", ((string)(null)), table22, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter on roomsMin")]
        public void RetrieveLeaseOfferListWithFilterOnRoomsMin()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter on roomsMin", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 149
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table23.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "1",
                            "750"});
                table23.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "2",
                            "950"});
                table23.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "3",
                            "1000"});
#line 150
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table23, "Given ");
#line hidden
#line 155
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'roomsMin=2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 156
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 157
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table24.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "3",
                            "1000"});
                table24.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "2",
                            "950"});
#line 158
 testRunner.And("The pageable content items should be like :", ((string)(null)), table24, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter on monthlyRentMin")]
        public void RetrieveLeaseOfferListWithFilterOnMonthlyRentMin()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter on monthlyRentMin", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 163
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table25.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
                table25.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
                table25.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "2",
                            "1000"});
#line 164
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table25, "Given ");
#line hidden
#line 169
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'monthlyRentMin=751\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 170
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 171
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table26.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "2",
                            "1000"});
                table26.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
#line 172
 testRunner.And("The pageable content items should be like :", ((string)(null)), table26, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter on monthlyRentMax")]
        public void RetrieveLeaseOfferListWithFilterOnMonthlyRentMax()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter on monthlyRentMax", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 177
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table27.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
                table27.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
                table27.AddRow(new string[] {
                            "3",
                            "Offer number 2",
                            "65",
                            "2",
                            "1000"});
#line 178
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table27, "Given ");
#line hidden
#line 183
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'monthlyRentMax=951\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 184
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 185
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table28.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "50",
                            "1",
                            "950"});
                table28.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "750"});
#line 186
 testRunner.And("The pageable content items should be like :", ((string)(null)), table28, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with combined filters")]
        public void RetrieveLeaseOfferListWithCombinedFilters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with combined filters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 191
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table29.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "800"});
                table29.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "40",
                            "1",
                            "900"});
                table29.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "56",
                            "2",
                            "1000"});
                table29.AddRow(new string[] {
                            "4",
                            "Offer number 4",
                            "65",
                            "3",
                            "1000"});
                table29.AddRow(new string[] {
                            "5",
                            "Offer number 5",
                            "80",
                            "3",
                            "1500"});
#line 192
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table29, "Given ");
#line hidden
#line 199
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'monthlyRentMin=900&s" +
                        "urfaceMax=64\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 200
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 201
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'1\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table30.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "56",
                            "2",
                            "1000"});
                table30.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "40",
                            "1",
                            "900"});
#line 202
 testRunner.And("The pageable content items should be like :", ((string)(null)), table30, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with both filter and pagination")]
        public void RetrieveLeaseOfferListWithBothFilterAndPagination()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with both filter and pagination", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 207
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table31.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "800"});
                table31.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "40",
                            "1",
                            "900"});
                table31.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "56",
                            "2",
                            "950"});
                table31.AddRow(new string[] {
                            "4",
                            "Offer number 4",
                            "65",
                            "3",
                            "1000"});
                table31.AddRow(new string[] {
                            "5",
                            "Offer number 5",
                            "80",
                            "3",
                            "1500"});
#line 208
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table31, "Given ");
#line hidden
#line 215
 testRunner.When("I make a GET request on lease-offers endpoint with pagination : \'pageSize=2&page=" +
                        "2&orderBy=monthlyRent&order=Desc\' and filter : \'monthlyRentMin=900\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 216
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 217
 testRunner.And("The pageable infos should be like : {CurrentPage : \'2\', TotalPage : \'2\', PageSize" +
                        " : \'2\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table32.AddRow(new string[] {
                            "3",
                            "Offer number 3",
                            "56",
                            "2",
                            "950"});
                table32.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "40",
                            "1",
                            "900"});
#line 218
 testRunner.And("The pageable content items should be like :", ((string)(null)), table32, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter that does not have macthing")]
        public void RetrieveLeaseOfferListWithFilterThatDoesNotHaveMacthing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter that does not have macthing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 223
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
                table33.AddRow(new string[] {
                            "1",
                            "Offer number 1",
                            "18",
                            "3",
                            "800"});
                table33.AddRow(new string[] {
                            "2",
                            "Offer number 2",
                            "40",
                            "1",
                            "900"});
#line 224
 testRunner.Given("The following list of lease offer is present in the system", ((string)(null)), table33, "Given ");
#line hidden
#line 228
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'monthlyRentMax=750\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 229
 testRunner.Then("The response Status code should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 230
 testRunner.And("The pageable infos should be like : {CurrentPage : \'1\', TotalPage : \'0\', PageSize" +
                        " : \'10000\'}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "LeaseOfferID",
                            "Title",
                            "Surface",
                            "Rooms",
                            "MonthlyRent"});
#line 231
 testRunner.And("The pageable content items should be like :", ((string)(null)), table34, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with wrong filter field name")]
        public void RetrieveLeaseOfferListWithWrongFilterFieldName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with wrong filter field name", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 234
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 235
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 236
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'uknownFieldName=18\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 237
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with wrong numeric filter field value")]
        public void RetrieveLeaseOfferListWithWrongNumericFilterFieldValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with wrong numeric filter field value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 239
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 240
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 241
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'surfaceMin=WrongValu" +
                        "e\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 242
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with empty filter field value")]
        public void RetrieveLeaseOfferListWithEmptyFilterFieldValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with empty filter field value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 244
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 245
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 246
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'surfaceMin=\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 247
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with filter field name only")]
        public void RetrieveLeaseOfferListWithFilterFieldNameOnly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with filter field name only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 249
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 250
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 251
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'surfaceMin\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 252
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with duplicate filter field")]
        public void RetrieveLeaseOfferListWithDuplicateFilterField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with duplicate filter field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 254
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 255
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 256
 testRunner.When("I make a GET request on lease-offers endpoint with filter : \'surfaceMin=18&surfac" +
                        "eMin=60\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 257
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with wrong page size")]
        public void RetrieveLeaseOfferListWithWrongPageSize()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with wrong page size", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 259
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 260
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 261
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'pageSize=-1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 262
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with wrong order field name")]
        public void RetrieveLeaseOfferListWithWrongOrderFieldName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with wrong order field name", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 264
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 265
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 266
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=unknown\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 267
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with wrong order value")]
        public void RetrieveLeaseOfferListWithWrongOrderValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with wrong order value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 269
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 270
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 271
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'orderBy=leaseOfferI" +
                        "d&order=ascendant\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 272
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve lease offer list with order but no order field")]
        public void RetrieveLeaseOfferListWithOrderButNoOrderField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve lease offer list with order but no order field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 274
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 275
 testRunner.Given("Whatever data I have in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 276
 testRunner.When("I make a GET request on lease-offers endpoint with arguments \'order=Asc\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 277
 testRunner.Then("The response Status code should be \'400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
