//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fonenako_service.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("fonenako_service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string order_whithout_orderby {
            get {
                return ResourceManager.GetString("order_whithout_orderby", resourceCulture);
            }
        }
        
        internal static string unknown_order_value {
            get {
                return ResourceManager.GetString("unknown_order_value", resourceCulture);
            }
        }
        
        internal static string unknown_order_field_name {
            get {
                return ResourceManager.GetString("unknown_order_field_name", resourceCulture);
            }
        }
        
        internal static string requested_page_index_not_valid {
            get {
                return ResourceManager.GetString("requested_page_index_not_valid", resourceCulture);
            }
        }
        
        internal static string requested_page_size_not_valid {
            get {
                return ResourceManager.GetString("requested_page_size_not_valid", resourceCulture);
            }
        }
        
        internal static string invalid_lease_offer_id {
            get {
                return ResourceManager.GetString("invalid_lease_offer_id", resourceCulture);
            }
        }
    }
}
